import 'clue.dart';

/// 专升本 CRM 核心真实学员线索数据永久安全种子（100% 真实数据保全）
class InitialRealClues {
  static List<Clue> getClues() {
    return [
      Clue(
        id: '1789808569912',
        wxNick: '怡然自乐',
        wxId: '',
        phone: '',
        grade: '25级',
        school: '驻马店幼儿师范',
        subject: '美术专业综合',
        source: '自招',
        classType: '暑假周末班',
        status: ClueStatus.following,
        intentLevel: IntentLevel.medium,
        ownerName: '超级管理员',
        createTime: DateTime.parse('2026-09-19T17:02:49.912'),
        visitLogs: [],
      ),
      Clue(
        id: '1789783775467',
        wxNick: '张博涵',
        wxId: '',
        phone: '',
        grade: '25级',
        school: '河南艺术',
        subject: '美术专业综合',
        source: '自招',
        classType: '暑期集训班',
        status: ClueStatus.following,
        intentLevel: IntentLevel.medium,
        ownerName: '李广东',
        createTime: DateTime.parse('2026-09-19T10:09:35.467'),
        visitLogs: [],
      ),
      Clue(
        id: '1789783614360',
        wxNick: '小鱼',
        wxId: '',
        phone: '',
        grade: '25级',
        school: '河南轻工',
        subject: '美术专业综合',
        source: '自招',
        classType: '暑假周末班',
        status: ClueStatus.following,
        intentLevel: IntentLevel.medium,
        ownerName: '李广东',
        createTime: DateTime.parse('2026-09-19T10:06:54.360'),
        visitLogs: [],
      ),
      Clue(
        id: '1789782969895',
        wxNick: '温柔可爱',
        wxId: '',
        phone: '',
        grade: '25级',
        school: '',
        subject: '管理学',
        source: '自招',
        classType: '暑期集训班',
        status: ClueStatus.contacted,
        intentLevel: IntentLevel.medium,
        ownerName: '超级管理员',
        createTime: DateTime.parse('2026-09-19T09:56:09.895'),
        visitLogs: [
          VisitLog(
            id: '1789808427917',
            clueId: '1789782969895',
            contactMethod: ContactMethod.wechat,
            visitResult: VisitResult.normal,
            visitContent: '还在跟进，约中秋节后的课吧',
            createTime: DateTime.parse('2026-09-19T17:00:27.916'),
          ),
        ],
      ),
      Clue(
        id: '1789782678573',
        wxNick: '林建',
        wxId: '',
        phone: '',
        grade: '25级',
        school: '林州建筑',
        subject: '美术专业综合',
        source: '自招',
        classType: '暑期集训班',
        status: ClueStatus.contacted,
        intentLevel: IntentLevel.medium,
        ownerName: '超级管理员',
        createTime: DateTime.parse('2026-09-19T09:51:18.573'),
        visitLogs: [
          VisitLog(
            id: '1789889657738',
            clueId: '1789782678573',
            contactMethod: ContactMethod.wechat,
            visitResult: VisitResult.normal,
            visitContent: '再次跟进网课的事情，微信没有回复！',
            createTime: DateTime.parse('2026-09-20T15:34:17.736'),
          ),
          VisitLog(
            id: '1789808222318',
            clueId: '1789782678573',
            contactMethod: ContactMethod.wechat,
            visitResult: VisitResult.followUp,
            visitContent: '发微信告知周末班和网课已开课，未回复微信',
            createTime: DateTime.parse('2026-09-19T16:57:02.317'),
          ),
        ],
      ),
      Clue(
        id: '1789782569032',
        wxNick: '金闪闪想出去玩儿',
        wxId: '',
        phone: '',
        grade: '25级',
        school: '河南经贸',
        subject: '美术专业综合',
        source: '自招',
        classType: '暑期集训班',
        status: ClueStatus.contacted,
        intentLevel: IntentLevel.medium,
        ownerName: '超级管理员',
        createTime: DateTime.parse('2026-09-19T09:49:29.032'),
        visitLogs: [
          VisitLog(
            id: '1789889721731',
            clueId: '1789782569032',
            contactMethod: ContactMethod.wechat,
            visitResult: VisitResult.normal,
            visitContent: '告知国庆节正常上课，如果不方便过来，可以拍视频看教室上课情况和环境，微信未回复！',
            createTime: DateTime.parse('2026-09-20T15:35:21.729'),
          ),
          VisitLog(
            id: '1789808490186',
            clueId: '1789782569032',
            contactMethod: ContactMethod.wechat,
            visitResult: VisitResult.normal,
            visitContent: '已告知上一届状元学姐同一个专业和学校，今天约试听课没回复！',
            createTime: DateTime.parse('2026-09-19T17:01:30.185'),
          ),
        ],
      ),
      Clue(
        id: '1789746533827',
        wxNick: '卡厄斯兰那',
        wxId: '',
        phone: '',
        grade: '25级',
        school: '河南物流（平原新区）',
        subject: '美术专业综合',
        source: '自招',
        classType: '暑期集训班',
        status: ClueStatus.attended,
        intentLevel: IntentLevel.high,
        ownerName: '超级管理员',
        createTime: DateTime.parse('2026-09-18T23:48:53.827'),
        visitLogs: [
          VisitLog(
            id: '1789808283749',
            clueId: '1789746533827',
            contactMethod: ContactMethod.wechat,
            visitResult: VisitResult.normal,
            visitContent: '已告知周末班开课，回复是需要跟家里商量报名费的事情！',
            createTime: DateTime.parse('2026-09-19T16:58:03.748'),
          ),
        ],
      ),
      Clue(
        id: '1789746438262',
        wxNick: '柟',
        wxId: '',
        phone: '',
        grade: '25级',
        school: '焦作工贸职业学院',
        subject: '高等数学',
        source: '自招',
        classType: '暑期集训班',
        status: ClueStatus.following,
        intentLevel: IntentLevel.medium,
        ownerName: '超级管理员',
        createTime: DateTime.parse('2026-09-18T23:47:18.262'),
        visitLogs: [],
      ),
      Clue(
        id: '1789746292333',
        wxNick: '蒋老师学生',
        wxId: '',
        phone: '',
        grade: '25级',
        school: '河南艺术职业学院',
        subject: '美术专业综合',
        source: '自招',
        classType: '暑期集训班',
        status: ClueStatus.contacted,
        intentLevel: IntentLevel.medium,
        ownerName: '超级管理员',
        createTime: DateTime.parse('2026-09-18T23:44:52.333'),
        visitLogs: [
          VisitLog(
            id: '1789869382015',
            clueId: '1789746292333',
            contactMethod: ContactMethod.wechat,
            visitResult: VisitResult.followUp,
            visitContent: '下雨了，约下次去学校见面！',
            createTime: DateTime.parse('2026-09-20T09:56:22.013'),
          ),
          VisitLog(
            id: '1789799289593',
            clueId: '1789746292333',
            contactMethod: ContactMethod.wechat,
            visitResult: VisitResult.followUp,
            visitContent: '约了20号来试听',
            createTime: DateTime.parse('2026-09-19T14:28:09.592'),
          ),
        ],
      ),
      Clue(
        id: '1789746157788',
        wxNick: '我',
        wxId: '',
        phone: '',
        grade: '25级',
        school: '轻工学院嵩山路',
        subject: '美术专业综合',
        source: '自招',
        classType: '暑期集训班',
        status: ClueStatus.following,
        intentLevel: IntentLevel.medium,
        ownerName: '超级管理员',
        createTime: DateTime.parse('2026-09-18T23:42:37.788'),
        visitLogs: [],
      ),
      Clue(
        id: '1789745780981',
        wxNick: '袁睿琪',
        wxId: '',
        phone: '',
        grade: '25级',
        school: '河南工贸',
        subject: '美术专业综合',
        source: '自招',
        classType: '暑期集训班',
        status: ClueStatus.enrolled,
        intentLevel: IntentLevel.high,
        ownerName: '超级管理员',
        createTime: DateTime.parse('2026-09-18T23:36:20.981'),
        visitLogs: [
          VisitLog(
            id: '1789745851232',
            clueId: '1789745780981',
            contactMethod: ContactMethod.wechat,
            visitResult: VisitResult.normal,
            visitContent: '提前上周末课！',
            createTime: DateTime.parse('2026-09-18T23:37:31.231'),
          ),
        ],
      ),
    ];
  }
}
